create table categorias(
    ID int AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION varchar(100),
    NOMBRE varchar(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

create table clientes(
   ID int AUTO_INCREMENT PRIMARY KEY,
   NOMBRE varchar(100),
   RUT varchar(100),
    TELEFONO varchar(100),
   EMAIL varchar(100),
   CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);  

    create table direcciones(
    ID int AUTO_INCREMENT PRIMARY KEY,
    CIUDAD varchar(100),
    DIRECCION varchar(100),
    NUMERO_CASA varchar(100),
    AGENCIA_PREFERIDA varchar(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

    create table emprendimientos(
    ID int AUTO_INCREMENT PRIMARY KEY,
    EMPRENDIMIENTO varchar(100),
    CLIENTE varchar(100),
    WHATSAPP varchar(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

    create table productos(
    ID int AUTO_INCREMENT PRIMARY KEY,
    NOMBRE varchar(100),
    PRECIO varchar(100),
    STOCK_CANTIDAD varchar(100),
    COSTO varchar(100),
    DESCRIPCION varchar(100),
    FOTO varchar(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);